language: node_js
node_js:
  - '10.16.3'
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod --base-href https://ivankubrick.github.io/bel-aktiv-project/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/belaktiv
  on:
    branch: master
